#!/usr/bin/env bash
# Replace a line with multiple lines with sed
apt-get update
apt-get install -y nginx

mkdir -p /var/www/test/html
touch /var/www/test/html/index.html
echo "Hello World!" > /var/www/test/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80;
    root   /var/www/test/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
